### ISSUE TITLE
Use youtube to store playlists

### ISSUE THREAD

**Issue by michael-jerred** [MeoMix/StreamusChromeExtension#304]
Currently you can import all the songs from a youtube playlist into streamus, but when modifying that playlist in streamus the youtube one is not updated.

It would be nice to be able to this, as then playlists could be shared with people that don't have streamus, and would reduce (eliminate?) the need for a backend server.

**Comment by MeoMix** [comment]
Merging into another issue

**Comment by DaFrik** [comment]
MeoMix, thanks for creating streamus. As a "no music no life" person, I would like to carry my playlist everywhere, I used to use youtube as my playlist "storage" as there are app like "PVSTAR+" on android and others on iPad that can read off youtube playlist, but for desktop i really like streamus (dispite the fact that i can never get the "radio" feature working), i wonder if you have worked with creator of PVSTAR+ or similar software that they can import streamus playlist such as : https://streamus.com/share/playlist/08ae3c1f0c4d/so_in_love

**Comment by MeoMix** [comment]
Well, PVSTAR+ was removed the app store in December for ToS violations last I checked. Maybe they'e gotten themselves back on the store, but yeah.

The reason Streamus doesn't support this is two-fold:

1) I want to add support for SoundCloud and expand to other APIs in the future. If your Streamus playlist has songs from SoundCloud & YouTube and you want to export it to a YouTube playlist... well, that's not going to work very well.

2) I would need to add support for authenticating YouTube user accounts. That's opening a whole new box full of issues to support, I am sure. And again, I am looking to make Streamus a platform-agnostic music service rather than deeply couple myself with one service. This makes logging into YouTube lower priority than getting SoundCloud support.
