### ISSUE TITLE
Song cannot be played repeat error continues

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#327]
If user puts a single song which has been removed from YouTube into the stream and tries to play it then Streamus infinite loops on the song, apparently.

**Comment by zevz** [comment]
I feel like this issue is more important that it might appear as explained here. If you import let's say a youtube playlist of 80 songs, whenever one of those songs gets removed from youtube and streamus tries to play it, the extension will get stuck and the playlist won't continue. This can happen constantly to videos as they are reuploaded, taken down etc for various reasons.

**Comment by MeoMix** [comment]
I am aware. The problem is that it if I skip the song and all the songs in the playlist are unplayable then it also repeats infinitely. I need to make other architecture changes to be able to detect if all songs are unplayable before I can actually fix the issue. Just dumbly skipping it only pushes the problem around.

**Comment by MeoMix** [comment]
Since I reverted this change the discussion should be continued over at #380
