### ISSUE TITLE
Add crossfade

### ISSUE THREAD

**Issue by narendrans** [MeoMix/StreamusChromeExtension#339]
Support for crossfade would be great.

**Comment by bradisbell** [comment]
Just a suggestion on this for implementation...  Rather than purely crossfading, fade out the previous track over 4 seconds or so and start the next track at full volume about halfway through that fade.  This isn't always super smooth because you don't know the audio in the tracks and what works, but for a lot of music this works well.

**Comment by MeoMix** [comment]
This is a lot more difficult to implement than people give credit. To be able to cross-fade you need to be able to play two tracks at the same time. That means using just a single embedded YouTube player is not an option. Also, songs can buffer, so need to make sure the next song is loaded in time for crossfading to actually work. And finally, YouTube 'remembers' the volume and muted state of players. So, if you mute one of the two players, the other one's "remembered" state is now muted. That means that if you go to YouTube.com... your songs are muted, etc.

Those are the main factors which have barred me from implementing this feature. If someone wants to take a stab at it, by all means, but I think there's a lot shinier, lower hanging fruit to be had currently.

**Comment by MeoMix** [comment]
I really just don't see this happening anywhere in the next 6+ months. There's so much to do :( Closing for now, but I'm sure I won't forget it.
