### ISSUE TITLE
Improve conveyance of state through icon

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#364]
Hey everyone,

With the advent of Streamus' new UI.. the material design feel has made some people feel like the S icon is drab and and out of place. I'm not ecstatic over it, but I don't feel like it's the worst thing ever, either.

My two requirements for the icon are that it be able to change colors to represent play/paused state at a glance and that it also be able to convey the volume at a glance. Perhaps the second issue isn't quite as pressing, but it would still be nice to preserve existing functionality.

Does anyone have any ideas on how the icon could be improved while maintaining functionality? 

Here's a guide to material design icons: http://www.google.com/design/spec/style/icons.html

**Comment by bradisbell** [comment]
I actually really like your icon.  It's unique and recognizable in an area that has many other icons on my browser.

I think that on color, if possible you should animate the icon (slowly) to indicate playing while not being distracting.  Either that, or add a sub-icon for playback.  It isn't universally clear that green in the log means its playing, especially since that part of the S is... part of the S.  Yellow to me indicates something wrong rather than paused.  

Maybe something like this?

![streamus_icon128_play](https://cloud.githubusercontent.com/assets/1097509/5849536/5136766e-a1ac-11e4-8e08-c42305d033e4.png)
![streamus_icon128_pause](https://cloud.githubusercontent.com/assets/1097509/5849537/51391bc6-a1ac-11e4-93fe-3603dcb880fb.png)

**Comment by MeoMix** [comment]
The icon can, in fact, be animated with some effort. Right now Streamus' icon is shown with just an image file. However, Chrome's icon API actually supports a canvas element. Crazy, right? So, with some effort, the icon could be re-drawn on canvas which would open up lots of neat effects.

I think that the icons look fine at this scale, but at 16px * 16px you lose a lot of that clarity. I haven't actually played with it, though. I will admit that most people don't really "get" what's going on with the icon. Maybe the green and yellow, but not the red and certainly not the bars. Ah well.
