### ISSUE TITLE
"An error was encountered" notification when adding any video to any playlist

### ISSUE THREAD

**Issue by hypershadsy** [MeoMix/StreamusChromeExtension#366]
![1421870850](https://cloud.githubusercontent.com/assets/3746656/5844285/c7dd3b30-a180-11e4-9bdb-578167caa673.png)
![1421871040](https://cloud.githubusercontent.com/assets/3746656/5844284/c7d91212-a180-11e4-93c1-1d93a4d04288.png)

Chrome Linux x64. I could add a video to this playlist 2 days ago.

I tried many videos, none worked. I tried a different target playlist, nothing. I made a new playlist from within the extension, nothing. There's no printing in the console.

**Comment by MeoMix** [comment]
Hummmm. 

Can you go to chrome://extensions/, check the checkbox that says 'developer mode', click 'background.html' which will cause another developer console to pop-up and then try again?

Should be some errors logged in that one as this is more of a background process issue rather than a foreground.

**Comment by hypershadsy** [comment]
No errors in that console besides these 
<http://stackoverflow.com/questions/24490323/google-chrome-cast-sender-error-if-chrome-cast-extension-is-not-installed-or-usi>, 
yet the notification remains.

**Comment by MeoMix** [comment]
Is it only adding songs in that fashion which does not work? Can you do it through the search in Streamus? Or through the context menu on YouTube?

**Comment by hypershadsy** [comment]
Of the three options "Text selection", "Youtube links", "Youtube pages", 
I only had pages enabled. I enable all of them and do some tests.

The ways I know of to add to a playlist are to 1. drag it from the 
stream (this works), 2. right click link -> save -> myplaylist (this 
works), 3. from a youtube page (this does not work).

**Comment by MeoMix** [comment]
That is super weird.

I wonder if something is intercepting the postMessage and corrupting the data.

You can see the code being ran here, sorry it's a bit messy. All the inject code is messy since I don't bring frameworks into the injection:

https://github.com/MeoMix/StreamusChromeExtension/blob/master/src/js/inject/youTubeInject.js#L125

Maybe it's failing to find the video-stream element? Is your YouTube a Flash player?

**Comment by hypershadsy** [comment]
I ran these commands. YT's $ returns the element and not a JQuery object 
so the output is different. But it should give you an idea, I hope!

![testingimagefromemail](http://i.imgur.com/J0jb5kt.png)

**Comment by MeoMix** [comment]
If you right-click on the video element is it a flash or HTMl5 context menu?

If it's flash then I think another extension is forcing YouTube to flash which is breaking Streamus :(

**Comment by hypershadsy** [comment]
It's HTML5. I can right click it and "About the HTML5 player". Disabling 
all my extensions does nothing.

**Comment by MeoMix** [comment]
Did you disable all your other extensions and then restart Streamus by disabling it and then re-enabling it? Just curious.. not trying to send you through a bunch of hoops.

Also, once you restart Streamus, you'll need to refresh the YouTube page you're on. Restarting the extension breaks postMessages to websites which were already loaded.

**Comment by hypershadsy** [comment]
I disabled all extensions, restarted, enabled Streamus, restarted, still 
broken.

**Comment by MeoMix** [comment]
Understood. Give me a bit of time to think up some ways to debug this. Sorry for the trouble.

**Comment by MeoMix** [comment]
Fixed it. YouTube's HTML mark-up changed which was the issue.
