### ISSUE TITLE
Allow for playlists to be shown in SearchResults

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#373]
This is probably more complicated than it seems.

First, the architecture of Streamus needs to change a bit. SearchResult has a reference to a Song object right now. Instead, it'll need to be able to have a reference to a Song or a Playlist.

It probably doesn't make sense to pull all of the Playlist's Songs when just showing the playlist in SearchResults. That means we'll have to pull songs once the user has shown intent to use that playlist. That's an async action where as currently all the data for a song is known making it a synchronous action.

Furthermore, one can drag-and-drop a playlist object into the stream. I suspect it would be best to convert that playlist object into a bunch of songs at that point instead of just showing it as one, playlist item. That'll have its own set of challenges.

**Comment by michael-jerred** [comment]
This could be done progressively.

Step 1. Show playlists in the search results, but dragging it to the stream or saving to a playlist does nothing, all you can do is right-click and copy URL.
Step 2. Implement 'expanding' of the playlist into its songs when adding to the stream / saving to a playlist. This should be easy actually because this function already exists in the create playlist from URL dialog.

Actually now that I think about it step 2 should be pretty trivial anyway.

**Comment by silviubogan** [comment]
It will be cool if Streamus will offer the option to queue YouTube playlists without transforming the playlists in separate songs. So if a playlist is updated on the YouTube side, the user will still listen to all the new songs added in the playlist. And it would be even better if the user could mix songs and YouTube playlists in the Now Playing (Queue) section.

**Comment by MeoMix** [comment]
@michael-jerred I agree that expanding it is the way to go, just so much to do! I have barely gotten to code at all in a week :( 

@silviubogan Your feature request is a duplicate of #16 :)

**Comment by MeoMix** [comment]
Closing in favor of #21
