### ISSUE TITLE
Playing a new playlist should automatically clear the current stream

### ISSUE THREAD

**Issue by tevert** [MeoMix/StreamusChromeExtension#405]
In most media players, the convention when explicitly playing a new thing is to clear the current play queue. Unless there's a usability concern here that I missed, Streamus should probably follow that convention. 

Currently, it appends the playlist to the current stream.

**Comment by MeoMix** [comment]
Somewhat agree, somewhat disagree.

If I have two playlists "Trap" and "Electro" and want to throw them
all on for a party in random order then I'd click 'Add Playlist' x2
and enable shuffle. Mixing multiple playlists together wouldn't be
possible without some other button if I made this change.

Thoughts?

**Comment by tevert** [comment]
It looks like there's an "add" button too, the plus sign between "play" and "delete", which also appends the songs to the stream, so that would still be possible. 

Right now, the only functional difference is that "play" also jumps to the newly added songs and starts playing.

**Comment by MeoMix** [comment]
Hummm, yeah. Okay, that makes more sense. Add would allow you to mix
playlists, but play would clear your stream and put the playlist into
it.

Some other concerns are:

- If I hit the 'play' button on a single search result.. the stream
probably shouldn't clear itself since only one song is being added.

- What if I have multiple songs selected? Is there a limit to the
number of songs which would need to be selected before clearing the
stream?

- Songs in the stream aren't guaranteed to be saved anywhere so the
user could experience loss of data if I clear the stream without
prompting... but then it's really just the same thing as clicking the
trashcan and then clicking play.

**Comment by tevert** [comment]
The search results still have the play button, so you might be able to get away with just reversing the position of the add and play buttons. However, that last scenario in particular could be troublesome.... looking at how Spotify behaves, it looks like it just throws out the current list. Not to say that's ideal though, a potentially better flow would be asking for confirmation, and maybe saving off the stream into a temp playlist. At that point you're talking about a pretty complex feature though.
