### ISSUE TITLE
Stream Youtube audio files instead of embedding iframe player

### ISSUE THREAD

**Issue by romaincointepas** [MeoMix/StreamusChromeExtension#411]
First, thanks for Streamus, this is a really great product.

As chrome extensions are not restricted by same-origin policy, you could extract and play Youtube audio streams.
This would decrease initial buffering time and greatly decrease bandwidth/CPU use (especially if one wants high quality audio). This would also make caching possible.

Reference:
- http://en.wikipedia.org/wiki/YouTube#Quality_and_formats (itag 171, 171, 139, 140, 141 are audio files)
- Stream URL extraction: https://github.com/fent/node-ytdl (it's a pure JS node library, easily portable).

BTW, I was the maker of the HipHop desktop app, I think we launched around the same time with Streamus v1 (http://cl.ly/image/3K1h1E2r2S0h).

**Comment by MeoMix** [comment]
I cannot! I'm actually going the other way. Since Streamus has gained the attn of YouTube it's in my best interest to adhere to their Terms of Service as best possible.

The Chromium team is working on whitelisting Streamus in the Chrome browser so that Streamus can use Chrome Panels to make the <video> element visible in an unobtrusive manner. It's going to be awesome :D

**Comment by romaincointepas** [comment]
That's cool! Out of curiosity, aren't you breaking their TOS by not displaying the video with the audio?

**Comment by MeoMix** [comment]
I am right now. As stated, the Chromium team is going to whitelist Streamus so I can use chrome panels to show the video.

**Comment by romaincointepas** [comment]
Oh okay, I thought the player was going to be in a panel. Thanks for taking the time to answer, and good luck, it is really a great product!
