### ISSUE TITLE
YouTube API Broken on Chrome 40.0.2214.111

### ISSUE THREAD

**Issue by landlockedsurfer** [MeoMix/StreamusChromeExtension#417]
Hi,
StreamUS stopped working after latest Chrome update to version 40.0.2214.111. I also tried with a fresh Chrome Profile on MacOS Yosemite but it did not help.
Got this error in the background page console:
Untrusted origin: chrome-extension://jbnkffmindojffecdhbbmekbmkkfpmjd in www-embed-player.js:331
Let me know if I can provide you with more information to fix this problem.
Cheers,
Manfred

**Comment by MeoMix** [comment]
I'm aware. I know the fix for it. YouTube fixed a bug on their side
which Streamus was working around. I just need to change a few slashes
around in the origin. It'll be fixed ASAP.

**Comment by landlockedsurfer** [comment]
Cool! Thanks for the quick response!
Does this mean no more workaround using the chrome.webRequest API?

**Comment by MeoMix** [comment]
Nope, that's here to stay. Chrome extensions don't provide a Referer by design, https://code.google.com/p/chromium/issues/detail?id=429556

The change is going from: origin=chrome-extension:\\\\' + chrome.runtime.id;

to origin=chrome-extension://' + chrome.runtime.id;

**Comment by landlockedsurfer** [comment]
Working nicely again, thanks!
Interesting comments regarding your post on the Chromium issue tracker. Looks like nobody cared about servers who are checking the referer header.

**Comment by MeoMix** [comment]
When you say it's working nicely again -- are you talking about a debug version? The version deployed to the Chrome Web Store is stuck in pending review right now so the fix isn't in production yet. It would be scary if it started working again randomly.

And I agree... it seemed like a poor decision on their part -- which is why I voiced my concern, but, eh, it works to Streamus' advantage. :)

**Comment by MeoMix** [comment]
When you say it's working nicely again -- are you talking about a debug version? The version deployed to the Chrome Web Store is stuck in pending review right now so the fix isn't in production yet. It would be scary if it started working again randomly.

And I agree... it seemed like a poor decision on their part -- which is why I voiced my concern, but, eh, it works to Streamus' advantage. :)

**Comment by landlockedsurfer** [comment]
Sorry about the confusion... I used the latest version from https://github.com/MeoMix/StreamusChromeExtension once you have commited your patch.

**Comment by MeoMix** [comment]
Cool. Just wanted to make sure, no worries on confusion :D

**Comment by landlockedsurfer** [comment]
(using the "Load unpacked extension..." feature)

**Comment by landlockedsurfer** [comment]
I'm curious - how did you come to know that you need to use backslashes instead of regular slashes to make things work before 40.0.2214.11? Hope you did not have to dig into the sources of Google Chrome itself. ;-)

**Comment by MeoMix** [comment]
Oh man, I don't remember. It was a while ago. It might have just been a lucky guess of "I wonder if they messed up the slashes... oh, and I guess I have to escape them, too..." but it might have been from a bug report, too.

**Comment by landlockedsurfer** [comment]
Wow... that must have been a tough one, but it looks like you have solved the most tricky problems.

**Comment by MeoMix** [comment]
Heh. The trickiest one is yet to come. I still need to be able to show
video in an unobtrusive fashion. It looks like what's going to happen
is Streamus is going to be added to a whitelist inside of Chrome so
that it can utilize Chrome panels in the same way that Hangouts does,
but store a collapsible window with the YouTube video. This way I'm
not in violation of YouTube's Terms of Service.

However, there's probably a fair bit of architecture brainstorming
which is going to have to surround that change. :(

**Comment by landlockedsurfer** [comment]
I'm a little lost on what feature you want to implement. Do you have an issue for it with more details?

**Comment by MeoMix** [comment]
I don't, but I probably should.

If you check out this extension: https://chrome.google.com/webstore/detail/pip-video/anoelogknphkblfagnpdmpfpaddikbae?hl=en you'll see what I mean, though.

Basically, YouTube's Terms of Service prohibit not making a decent effort at showing a 200px * 200px video player. Streamus' popup page is destroyed whenever focus is lost. So, I can't host the video player there because audio playback would stop.

My solution to the issue was to host the video on the background page. Technically I am still hosting a YouTube video, but it's not actually visible to the end user. So, YouTube would like me to find a way to fix this at some point. They're understanding of the technical issues, though.

There's two ways to fix this -- either hosting the video inside of a Chrome panel, or using a <canvas> element to re-draw each frame of the video inside of the popup -- thus decoupling the visuals from the audio. 

I talked to YouTube about the options and they want me to go with the Chrome panel solution. However, Chrome panels aren't enabled by default for users. You have to go to chrome://flags, enable panels, and then restart the browser for them to work. That sucks and isn't practical.

Google knows that. So, for their Hangouts extension, which uses Chrome panels, they whitelisted their extension so that panels would still work for users even if they had not explicitly enabled them. I asked for that permission on their forums last year, but was told no way.

Now that I've been able to reach out to people higher up in the foodchain -- they're singing a different tune and are working with the Chromium team to get Streamus whitelisted. This will make it more of a possibility.

**Comment by woniesong92** [comment]
@MeoMix You saved Instant Music again Sean.
Btw, I am also in violation of TOS of YouTube because I am not showing videos for the same reason.
Would you mind recommending me the best person to contact to resolve the problem for Instant Music?

**Comment by landlockedsurfer** [comment]
Thanks for the detailed explanation. That was very insightful!

The PIP video extension looks great. I never heard about the panel feature. Bummer that they need to be enabled explicitly.

I'm glad you found the right people to make things work. The panel-based Streamus will look great!

Did you suggest to Google to show some fat YouTube logo instead of the 200px * 200px video player to make sure Streamus users are well aware of the fact that this song is brought to you by YouTube?

**Comment by MeoMix** [comment]
@woniesong92 You can try Ibrahim Ulukaya <ulukaya@google.com>. It took me about 9 months of reaching out to get a response from anyone in dev relations, though. So... good luck, lol.

@landlockedsurfer It's more about YouTube being able to tell their advertisers that their ads are actually being seen -- not about self-promotion. It's the same reason YouTube mobile apps stop working when you lock your phone screen.

**Comment by landlockedsurfer** [comment]
Ok, got it... can I also ask you how you managed to avoid video ads with Streamus? Maybe I haven't used it long enough yet but so far I haven't got any video ads.

**Comment by MeoMix** [comment]
For whatever reason setting the Referer to youtube.com prevents ads. I'm sure I'll be asked to support them at some point, though. :)
