### ISSUE TITLE
Small layout issue when window gets too short

### ISSUE THREAD

**Issue by magus424** [MeoMix/StreamusChromeExtension#579]
When I resize the window below a certain height, it stops respecting the width of the window anymore.

Working: http://i.imgur.com/MMCHEnV.png

Not: http://i.imgur.com/O6OXk8T.png (slightly shorter than above image)

**Comment by MeoMix** [comment]
Yeah, this is because of a weird hack I use to get Streamus to support full screen while also supporting fixed-dimensions in a Chrome extension.

https://github.com/MeoMix/StreamusChromeExtension/blob/Development/src/less/foreground.less#L35

I wonder how it could be written to support smaller dimensions, too. Maybe need something less hacky.

**Comment by magus424** [comment]
Ah, interesting... I might mess with it when I have some time then and see if I can figure out a tweak :)

**Comment by magus424** [comment]
Hmm... so after poking at this, I think the only solution would be to have a separate popup.html that adds an ID to make that static width/height, and have foreground.html be when you open in a tab (or call that tab.html or such)

(or vice versa, have foreground.html stay the popup and add a new page for the tab/app shortcut version)

**Comment by MeoMix** [comment]
I managed to solve it pretty simply with:

```
chrome.tabs.getCurrent(this._onChromeTabsGetCurrent.bind(this));

// Flag body with a class indicating whether view is in popup or tab so that CSS can react.
_onChromeTabsGetCurrent: function(tab) {
  $('body').addClass(_.isUndefined(tab) ? 'is-popup' : 'is-tab');
  this._showForegroundArea();
},
```
