### ISSUE TITLE
Setting to disable playing Youtube window in popup

### ISSUE THREAD

**Issue by tyaramis** [MeoMix/StreamusChromeExtension#591]
The new UI is nice. 
However, I use Streamus only for music streaming not for video playing. 
If you work in a office, and youtube videos run constantly on your monitor, first; it distracts your attention and secondly your co-works think that you are only looking youtube videos whole day.

Playing videos on pop up should be disabled using a setting key.

Thanks

**Comment by MeoMix** [comment]
Did you read any of the social media posts I made on FB, Twitter, Reddit, or the patch notes I released on GitHub?

Read here please: https://github.com/MeoMix/StreamusChromeExtension/releases/tag/v0.177

I'm legally required to show video in Streamus without the option to toggle it on/off otherwise I will be shut down.

You should use AdBlocking software to remove the video if you so desire. uBlock and AdBlock both have the ability to remove elements from pages.

Sorry.

**Comment by tyaramis** [comment]
Sorry I just oversighted the obligation part in release notes.
Is it possible to change the size of the popup video player? 
So that the video player will be sill displayed but in very small size.

Anyway thanks for the tips about AdBlock...

**Comment by MeoMix** [comment]
The minimum allowed size of the video player is 200px * 200px, https://developers.google.com/youtube/iframe_api_reference#Requirements

**Comment by tyaramis** [comment]
I see..

I could not remove the video player using AdBlock (Free Edition), since AdBlock is disabled if I open Streamus in a tab.

**Comment by MeoMix** [comment]
Hmmmm, you're right. That's odd. I wonder if there's a way to get that to
work. I can look into it in a while.

**Comment by tyaramis** [comment]
Ok. Great...
Thanks for the great tool anyway..
