### ISSUE TITLE
Issue about user experience and interface

### ISSUE THREAD

**Issue by cristiana214** [MeoMix/StreamusChromeExtension#593]
it could be better if there is an option in settings  to show the video or not. i personally like the old small width design it is user friendly. I don't want to show the video.Now i have hard time navigating. I don't like the part when i want to play the last song in the stream list and the pause/play delete option button cannot be clicked because the video is covering it. thank you hope you find the solutions.
![capture](https://cloud.githubusercontent.com/assets/5396875/8476469/909fc92e-2076-11e5-860d-3ebb24846aa9.PNG)

**Comment by turuto** [comment]
In the release notes it is said that playing the video is mandatory from youtube policies, so I'm afraid there is few things that can be done regarding to that but thinking of a better place.

**Comment by MeoMix** [comment]
I'm not allowed to remove the video. YouTube's forbid me from hiding it.

The video should temporarily hide itself when you hover over it to allow you to click the buttons it's hiding behind itself.

I'm going to work on giving the ability to pop it out into it's own window which you can minimize, but if you close that window then it'll re-appear in the UI. I think that's about all I can do.

**Comment by hdavidzhu** [comment]
Does Youtube have a specification for the smallest size that the video can appear? Would it also be possible if the video gets moved to another tab - or would that also be against policy? If the video can be made into (tiny) thumbnail size (that can expand), that would be pretty cool.

**Comment by MeoMix** [comment]
Yes, the smallest size is 200px * 200px, https://developers.google.com/youtube/iframe_api_reference#Requirements. The video is currently 200px tall and 16:9 ratio for better viewing. Its width could be slightly decrease, but it would make the videos much uglier.

It is against their policy to allow toggling off of the video in any manner. I tried doing that in a previous prototype and they shot it down telling me it needs to be permanently visible rather than toggled on at will.

**Comment by hdavidzhu** [comment]
(@MeoMix btw thanks putting together such an amazing extension)
I just skimmed over the requirements and I didn't see anything mentioned about opacity... maybe there's some easy way to toggle that to make it less obtrusive.

For me, I use it a lot at work, and I don't want others to think I'm just watching a bunch of Youtube videos when I look through songs. I think that the video screen can be moved _outside_ of the current wrapper box so that the controllers would not be blocked by a video screen. 

Also, it would be nice if the video be on the left of main screen rather than the lower right since chrome extension buttons are on the right side of the omnibar. When I move my mouse down, its much quicker to not move it all the way to the left. Therefore the controllers can still be concise, and the video can still be displayed.

I might fork it and try out some new styling in a few days, but these are just some of my current thoughts!

**Comment by MeoMix** [comment]
It's not directly mentioned in their requirements, but I have a direct line of communication with 4 people from YouTube and we've been going back-and-forth for months.

I argued pretty heavily for being able to toggle it off and got a flat out no: 
![](http://i.imgur.com/A393wtB.png)

Video on the left-side covers up song titles. Video on the right side just covers up buttons. If you hover over the video it should temporarily fade out so that you can interact with the buttons.

Feel free to provide mocks or submit ideas. I'm all for it.

**Comment by hdavidzhu** [comment]
I forked the branch, but I can't seem to get anything else working except for a blank page with some errors in loading the Chrome extension in my developer console. Since I'm not familiar with chrome extension development yet, it might be easier just to share with you this for a simple UI tweak:

![potentialdesign](https://cloud.githubusercontent.com/assets/3756871/8490452/32e51858-20f7-11e5-830b-ea90f61428ee.png)

I crudely moved the video to the left. Now there's a lot of real estate in the panel itself... You can shrink that (if you want) and get it close to 640px * 480px? (I'm not sure if that's a hard limit for Streamus... if it is then you can disregard my thoughts.)

This way the video is out of the way and won't make the controller feel too bulky.

**Comment by MeoMix** [comment]
You probably need to run "grunt less && grunt watch" to compile the LESS into CSS. The CSS isn't committed to GitHub.

It's not possible to do what you've shown. Chrome extensions have a maximum width/height of 800px * 600px because Chrome wants to try to prevent clever phishing attempts from extensions.

It's not possible to have extra, floating windows in chrome extensions. It would be possible to do with a chrome app, but that's a whole different can of worms.

**Comment by hdavidzhu** [comment]
Yep I've done those steps before. Here is my error:
```
Uncaught TypeError: Cannot read property 'getExposedProperties' of undefined
```

http://i.imgur.com/ytBvCNp.png

I just haven't taken the time to pick up extensions or look into the error yet, so I decided that picture would be more effective. I'm guessing the extension is already at the max 800 x 600 then?

**Comment by hdavidzhu** [comment]
![image](https://cloud.githubusercontent.com/assets/3756871/8490570/34e9e9ba-20f9-11e5-961d-b31aced5b8e5.png)

I think Less and Grunt and running fine too

**Comment by MeoMix** [comment]
Oh, I see.

If you go to chrome://extensions, and click 'background.html' underneath the extension, another dev tools will open up. Suspect it's because you need to copy src/js/background/key/youTubeAPIKey.js.example, drop the example part of from it, and then copy/paste the demo key in that file into the appropriate spot. I don't commit the production key.

**Comment by hdavidzhu** [comment]
Awesome thanks. Also, thanks for putting together great documentation!
And this is pretty sweet :smile: 

![image](https://cloud.githubusercontent.com/assets/3756871/8490621/ee53adbe-20f9-11e5-856c-efe0e8c826ae.png)

**Comment by MeoMix** [comment]
:D I did try! It's hard making nice docs as the only developer, but they're fun to do when too tired for other things.

**Comment by hdavidzhu** [comment]
@MeoMix 
Quick question: for some reason I can't find the `iframe` or any element associated with the Youtube player in the `Elements` view. I'm familiar with React and Backbone but not with Marionette. How can I inspect the Youtube element?

**Comment by Magentah** [comment]
Most things relating to the Youtube player are on the background page. The foreground page is displaying cached data as it's destroyed when it closes. To inspect the iframe for the player, go to chrome://extensions and open the background.html page. It's in the youtubePlayer div element, in the backgroundArea div.

**Comment by MeoMix** [comment]
Indeed. If the `<iframe>` was hosted on foreground.html then the audio would cease when the popup closed. So, it's hosted on the background page, but that makes the video not visible. So, I put a whole ton of effort into piping the video from the background to the foreground.

**Comment by MeoMix** [comment]
Video is now opened in a popup window instead. Closing!

**Comment by idmontie** [comment]
:+1: Does this mean a new release is coming soon?

**Comment by MeoMix** [comment]
I don't know yet. I have meetings with YouTube this week.
