### ISSUE TITLE
New UI bug

### ISSUE THREAD

**Issue by kevin-king** [MeoMix/StreamusChromeExtension#594]
Looks like most recent update introduced a significant UI regression. Can't get to some buttons on the right side. Using latest Chrome v43.

![screen shot 2015-07-02 at 9 36 06 am](https://cloud.githubusercontent.com/assets/4614395/8478202/cec2cac2-209d-11e5-96cc-b35e6117edab.png)

**Comment by MeoMix** [comment]
This is because you're using Chrome on >100% zoom and I needed to increase the dimensions of Streamus to hold the video.

I reported the bug to Google a while back, https://code.google.com/p/chromium/issues/detail?id=420382, and mentioned it in the patch notes, https://github.com/MeoMix/StreamusChromeExtension/releases/tag/v0.177.

Chrome extensions have a maximum width/height of 800px * 600px. Previously, Streamus used dimensions of 640px * 480px to support 125% page zoom (640 * 1.25 = 800, 480 * 1.25 = 600). However, now that I am forced to show a 200px * 200px video -- I didn't feel that Streamus had enough space to show it. So, I increased the dimensions of it, but that screws over people with higher zoom levels.

I'd like to give users the ability to control the size of the window, but it's going to take some work. Sorry.

**Comment by kevin-king** [comment]
You're correct, dropping Chrome zoom from 110% down to 100% in settings fixed it. Note for others: page specific zoom (command+plus) is still possible without messing up the extension dimensions.

Have my native resolution bumped up to 1920x1200 for more screen real estate and Chrome zoomed a bit so text is still easy to read. 

No worries though, thanks for the update! Bummer about the video policy, but still a great app!

**Comment by MeoMix** [comment]
Feel free to star that Chrome bug report I linked so that it can get more attention. I'd be able to support zoom levels if it was addressed. :) Thanks for not being too angry... been getting a lot of shit the last 24 hours.

**Comment by kevin-king** [comment]
Will do, no worries. I'm a dev too; I get it.

This is one of my most idolized open-source one-man-show apps! Don't let people's shit get you down :smile:

If I get some free time maybe I'll look into zoom control if you're cool with contributions.

**Comment by MeoMix** [comment]
Yeah of course I'm down with contributions.

I think it'd basically be adding a setting which uses JavaScript to overwrite the default CSS values for height/width, but only if Streamus isn't open in a tab and give the user some sliders to adjust the height/width to whatever they want within reason.

**Comment by MeoMix** [comment]
Closing this issue. Opening a new one for allowing custom controls.
