### ISSUE TITLE
Sean, just an idea on YouTube shutting Streamus down...

### ISSUE THREAD

**Issue by LNFWebsite** [MeoMix/StreamusChromeExtension#611]
I know that you've worked tremendously hard on this project and sincerely appreciate your work.

Instead of letting YouTube shut Streamus down because of its nature to be able to hide the video, market it _AS_ a video player...

For instance, you currently have the ability to open streamus in a tab. Make this the ONLY functionality available to users and constantly have the streaming video open within this tab.

Users may then cause the tab to go to the background of their own doing, letting them listen to streaming music without the video.

Market streamus as a YouTube enhancer that allows users to create a "Rolling playlist" of videos. It would then be seen as none other than another YouTube video player.

You would keep Streamus going, and would be conforming to YouTube's standards.

Just an idea...

**Comment by MeoMix** [comment]
This rebranding is indeed going to be happening to some extent.

It's a bit unfortunate because the word "Streamus" stands for "Stream music", but yeah, am aware it would help improve their perception of me. Still a lot of coding stuff to go, though, too.

**Comment by LNFWebsite** [comment]
Sean, could you distribute my new project to your listeners. It's far from perfection, but I think they could use it until you go back online. I appreciate it! https://github.com/LNFWebsite/Streamly

**Comment by LNFWebsite** [comment]
Sorry, forgot to tell you I changed my username HelpingHand1 => LNFWebsite

**Comment by MeoMix** [comment]
I responded to you on Reddit. As stated, simply interacting with YouTube's content will make you liable to play by their set of rules. Simply trying to skirt around not using their API is insufficient... :/

**Comment by LNFWebsite** [comment]
Yeah... But as far as I can tell, I'm not breaking any rules... Also, without using their API, Streamly is essentially invisible to them. It can be put on any web server.

**Comment by MeoMix** [comment]
Not invisible to lawyers :p If I'm going to spend my time developing something I want it to be able to be a legitimate music service. We'll see where that takes me.

**Comment by LNFWebsite** [comment]
And all the best luck to you. Streamly does not break any laws. There is no server side code and never will be with Streamly. It is more of a fallback for when other services cannot be found.

I have seen that Streamus has its own dedicated server. That's where things get smelly in the legal realm.

**Comment by MeoMix** [comment]
Streamus server is not even part of the equation regarding my issues with YouTube's legal department. It has never been brought up in any of our talks.

**Comment by LNFWebsite** [comment]
It kinda makes me wonder why... What does the server do?

**Comment by MeoMix** [comment]
localStorage is wiped whenever a Chrome extension is uninstalled and chrome.storage.sync is an incredibly small pipe for syncing data across PCs which can be easily filled.

The server stores a user's G+ ID associated with their playlists and songs so that their data is more persistent across machines / PC reformats / reinstalls. Additionally, it allows for sharing of playlists via streamus.com/share by offering an end-point for the URLs. Without this, you'd have to encode all the information into a URL which simply isn't realistic.

**Comment by MeoMix** [comment]
You can see all the table mappings here: https://github.com/MeoMix/StreamusServer/tree/development/Streamus/Dao/Mappings

**Comment by LNFWebsite** [comment]
> Additionally, it allows for sharing of playlists via streamus.com/share by offering an end-point for the URLs. Without this, you'd have to encode all the information into a URL which simply isn't realistic.

Why isn't this realistic? Encode the playlist in JSON format and run it through as base64.

Check out how this works: http://jbt.github.io/markdown-editor/

**Comment by MeoMix** [comment]
Well, doing the math a bit it looks like it _might_ be realistic, but still is just a horrible way to go about doing things. The maximum limit of a URL in Chrome is 2MB. Anything above that will start to crash the browser and, presumably, for weaker machines a lower value would be needed.

Base64 encoding size is: 4 \* Math.ceil(string.length / 3) or 1500000 characters roughly for 2MB.

Stripping out everything except for the bare minimum needed a song would be on average around 100 characters. That gives us an upper limit of songs of 15,000. Streamus itself handles that just fine, and people do have 2k+ song playlists already, but it's something to consider. Additionally, if I ever need to represent more data... like whether a song is YouTube or some other API, then the # of songs able to be shared continues to go down.

Other stuff:
- All shareable URLs would break whenever I make back-end changes for storing data or my back-end would need to be backwards compatible for all types of URLs.
- It's pretty bad UX to try and share something that long with a friend. Just because you can paste it into your URL bar doesn't mean you can paste it into a Facebook post, Reddit post, etc... those all have maximum character lengths which would start to come into play.
- Collaborative playlists are (were?) on the to do list. You cant' really collaborate with others on a playlist if the URL is static.

**Comment by LNFWebsite** [comment]
I didn't know about the 2MB limit on Chrome. Otherwise, every URL shortener could do away with the length troubles... But for the playlist collaboration, you would need the server side stuff.
